<?php

namespace App\Services\ThreeD;

/**
 * PROCEDURAL CASE CHASSIS.
 *
 * LOCAL FRAME (mm) IS THE CASE FRAME ITSELF, so BuildSceneService can drop it
 * straight into the scene at the origin:
 *   +X = case width  (glass panel at -X, motherboard tray at +X)
 *   +Y = case height (0 at the feet/floor, +Y to the roof)
 *   +Z = case depth  (rear I/O at -Z, front intake at +Z)
 *
 * A case is a shell, not a solid: it has to be possible to see the parts inside
 * it. So it is built as panels with real thickness, a PSU shroud, a front intake
 * mesh, a roof panel, and a glass side panel only where the catalogue says the
 * glass is (`specs.glass_panels`, e.g. "side" or "front,side").
 *
 * The parts it contains (fans, drive bays, radiator mounts) are generated by
 * CaseFans and are positioned from the case's OWN published specs -" rad_top and
 * rad_front radiator sizes, max_gpu, max_cooler, form factor -" so a case that
 * takes a 360mm top radiator is drawn with a 360mm top mount and one that does
 * not, is not.
 */
final class CaseGeometry implements PartGeometry
{
    private const PANEL_T = 4.0;      // sheet steel / aluminium, mm
    private const GLASS_T = 4.0;      // tempered glass, mm
    private const SHROUD_H = 90.0;    // PSU shroud height on a mid tower
    private const FOOT_H = 20.0;

    public function localFrame(): string
    {
        return 'Case local = case frame: +X width (glass at -X), +Y height (0=floor), +Z depth (rear at -Z)';
    }

    /**
     * Where things live inside the shell. BuildSceneService uses these instead
     * of hard-coding offsets, so the basement, the radiator mounts and the drive
     * cage all follow the case's real published dimensions.
     *
     * @return array<string, array{0: float, 1: float, 2: float}>
     */
    public function anchors(array $dims, array $specs, string $name, string $category): array
    {
        $w = (float) ($dims['x'] ?? 230);
        $h = (float) ($dims['y'] ?? 460);
        $d = (float) ($dims['z'] ?? 460);
        $form = strtolower((string) ($dims['form'] ?? 'mid-tower'));
        $mini = str_contains($form, 'mini') || str_contains($form, 'itx');
        $shrouder = $mini ? 60.0 : self::SHROUD_H;

        return [
            'psu_centre' => [0.0, self::FOOT_H + $shrouder * 0.5, -($d * 0.08)],
            'psu_top' => [0.0, self::FOOT_H + $shrouder, -($d * 0.08)],
            'roof' => [0.0, self::FOOT_H + $h, 0.0],
            'tray_face' => [$w / 2 - 22.0, self::FOOT_H + $shrouder, 0.0],
            // The board is mounted flat against the tray, whose face is on the +X
            // side, and extends AWAY from it across the case. MotherboardGeometry
            // draws the PCB from its own origin toward +X, so that origin has to
            // sit at the tray face MINUS the board's rear standoff.
            //
            // It used to be +($w / 2 - 12), which put the origin just INSIDE the
            // right-hand wall and then extended a 305mm ATX board a further 305mm
            // to the right - 190mm outside a 230mm case, and impossible for any
            // board larger than the case. Found by rendering the scene in a
            // browser and measuring it, which is the only way this shows up: the
            // geometry proofs check each part in isolation and never compared a
            // part against the case it has to fit inside.
            'board_origin' => [($w / 2) - 12.0, self::FOOT_H + $shrouder + 8.0, -($d / 2) + 12.0],
            'shroud_height' => [0.0, $shrouder, 0.0],
            'foot_height' => [0.0, self::FOOT_H, 0.0],
        ];
    }

    public function generate(array $dims, array $specs, string $name, string $category, array $context = []): array
    {
        $w = (float) ($dims['x'] ?? 230);
        $h = (float) ($dims['y'] ?? 460);
        $d = (float) ($dims['z'] ?? 460);

        $form = strtolower((string) ($dims['form'] ?? 'mid-tower'));
        $mini = str_contains($form, 'mini') || str_contains($form, 'itx');
        $glassSpec = strtolower((string) ($dims['glass'] ?? 'side'));
        $hasSideGlass = $glassSpec !== 'none' && $glassSpec !== '';
        $hasFrontGlass = str_contains($glassSpec, 'front');

        $shroodH = $mini ? 60.0 : self::SHROUD_H;

        // The published case height INCLUDES the feet, so the shell is built to
        // fill the remaining height rather than sitting on top of the full one.
        // Otherwise every rendered case claims to be 20mm taller than the size
        // the customer was quoted.
        $bodyH = max(120.0, $h - self::FOOT_H);

        $m = [];

        // --- Feet ----------------------------------------------------------
        // Inset from BOTH side walls. Adding the half-width to a signed inset
        // puts the right-hand feet outside the chassis entirely.
        $footInset = $d * 0.10;
        $footX = $w / 2 - 16.0;
        foreach ([[-1, -1], [-1, 1], [1, -1], [1, 1]] as [$sx, $sz]) {
            $m[] = Mesh::box(26.0, self::FOOT_H, 26.0, 'caseFoot',
                [$sx * $footX, self::FOOT_H / 2, $sz * ($d / 2 - $footInset)]);
        }
        $yBase = self::FOOT_H;

        // --- Structural panels ---------------------------------------------
        // Roof.
        $m[] = Mesh::box($w, self::PANEL_T, $d, 'casePanel', [0, $yBase + $bodyH - self::PANEL_T / 2, 0]);
        // Floor.
        $m[] = Mesh::box($w, self::PANEL_T, $d, 'casePanel', [0, $yBase + self::PANEL_T / 2, 0]);
        // Rear panel, with the I/O cutout implied by the motherboard sitting
        // against it.
        $m[] = Mesh::box(self::PANEL_T, $bodyH - $shroodH, $d, 'casePanel',
            [-(($w / 2) - self::PANEL_T / 2), $yBase + $shroodH + ($bodyH - $shroodH) / 2, 0]);

        // Motherboard tray: a real tray is perforated and offset from the glass,
        // which is what creates the cable-management gap.
        $trayX = $w / 2 - 22.0;
$m[] = Mesh::box(self::PANEL_T, $bodyH - $shroodH - 10.0, $d - 30.0, 'caseTray',
            [$trayX, $yBase + $shroodH + ($bodyH - $shroodH - 10.0) / 2, 12.0]);

        // Front intake panel -- solid, and separately a mesh.
        $m[] = Mesh::box($w, $bodyH - self::PANEL_T * 2, 10.0, 'caseFront',
            [0, $yBase + $bodyH / 2, $d / 2 - 5.0]);
        $meshCount = (int) max(6, floor(($bodyH - 60) / 12));
        $m[] = Mesh::stack($meshCount, ($bodyH - 60) / $meshCount,
            [$w - 26.0, 4.0, 3.0], 'y', 'caseMesh',
            [0, $yBase + $bodyH * 0.52, $d / 2 - 2.5], true);
        $m[] = Mesh::stack((int) max(3, floor(($w - 26) / 12)), ($w - 26) / max(3, (int) floor(($w - 26) / 12)),
            [3.0, $bodyH - 60.0, 3.0], 'x', 'caseMesh',
            [0, $yBase + $bodyH * 0.52, $d / 2 - 2.5], true);

        // --- Glass panels ---------------------------------------------------
        if ($hasSideGlass) {
            $m[] = Mesh::box(self::GLASS_T, $bodyH - 40.0, $d - 20.0, 'glass',
                [-(($w / 2) - self::GLASS_T / 2), $yBase + $bodyH / 2 + 6.0, 0]);
            // Glass frame: four real extrusions, so the panel reads as mounted.
            $m[] = Mesh::box(6.0, 8.0, $d - 16.0, 'caseTrim',
                [-(($w / 2) - 3.0), $yBase + $bodyH - 16.0, 0]);
            $m[] = Mesh::box(6.0, 8.0, $d - 16.0, 'caseTrim',
                [-(($w / 2) - 3.0), $yBase + 28.0, 0]);
        }
        if ($hasFrontGlass) {
            $m[] = Mesh::box($w - 10.0, $bodyH - 40.0, self::GLASS_T, 'glass',
                [0, $yBase + $bodyH / 2 + 6.0, $d / 2 - self::GLASS_T / 2]);
        }

        // --- PSU shroud / basement ------------------------------------------
        $m[] = Mesh::box($w, $shroodH, $d, 'caseShroud', [0, $yBase + $shroodH / 2, 0]);
        // Shroud top plate, with the real cable cut-outs along its rear edge.
        $m[] = Mesh::box($w, 2.0, $d, 'casePanel', [0, $yBase + $shroodH, 0]);
        $cutouts = $mini ? 2 : 3;
        for ($i = 0; $i < $cutouts; $i++) {
            $m[] = Mesh::box($w * 0.10, 3.0, 14.0, 'caseCutout',
                [-(($w / 2) - 20.0) + $i * ($w * 0.14), $yBase + $shroodH + 0.5, -($d / 2 - 34.0)]);
        }

        // --- Drive bays (real count per form factor) -------------------------
        $bays = $mini ? 1 : 2;
        for ($i = 0; $i < $bays; $i++) {
            $m[] = Mesh::box($w * 0.10, 101.6, 147.0, 'driveBay',
                [-(($w / 2) - 16.0), $yBase + $shroodH + 56.0, -($d / 2 - 80.0) - $i * 6.0]);
        }
        // 2.5" mounts behind the tray.
        $m[] = Mesh::stack($mini ? 2 : 4, 8.0, [$w * 0.08, 12.0, 70.0], 'y', 'driveBay',
            [-(($w / 2) - 18.0), $yBase + $shroodH + 30.0, $d / 2 - 60.0], false);

        // --- Front IO on the roof (real on every case in this catalogue) -----
        $ioZ = $d / 2 - 40.0;
        $ioY = $yBase + $bodyH - 4.0;
        $m[] = Mesh::box(60.0, 6.0, 22.0, 'caseIo', [-($w * 0.18), $ioY, $ioZ]);
        $m[] = Mesh::cyl(9.0, 5.0, 'y', 'casePowerButton', 18, [-($w * 0.30), $ioY, $ioZ]);
        $m[] = Mesh::stack(2, 16.0, [13.0, 4.0, 7.0], 'x', 'caseUsb', [-($w * 0.05), $ioY, $ioZ], false);
        // Audio jacks.
        for ($i = 0; $i < 2; $i++) {
            $m[] = Mesh::cyl(3.0, 5.0, 'y', 'caseJack', 10,
                [($w * 0.14) + $i * 9.0, $ioY, $ioZ]);
        }

        // --- Vertical accent strip down the front edge ------------------------
        // Purely decorative, brandless: no logo, no text, no watermark.
        $m[] = Mesh::box(4.0, $bodyH * 0.52, 4.0, 'caseLed',
            [-(($w / 2) - 10.0), $yBase + $bodyH * 0.42, $d / 2 - 12.0]);
        $m[] = Mesh::box(4.0, 4.0, $d * 0.44, 'caseLed',
            [-(($w / 2) - 10.0), $yBase + $bodyH - 16.0, 0]);

        return [
            'meshes' => $m,
            'meta' => [
                'form' => $form,
                'glass' => $glassSpec,
                'shrouder_height_mm' => round($shroodH, 2),
                'drive_bays' => $bays,
                'max_gpu_mm' => (int) ($dims['max_gpu'] ?? 0),
                'max_cooler_mm' => (int) ($dims['max_cooler'] ?? 0),
                'rad_top_mm' => (int) ($dims['rad_top'] ?? 0),
                'rad_front_mm' => (int) ($dims['rad_front'] ?? 0),
                'envelope' => ['x' => $w, 'y' => $h, 'z' => $d],
                'derivation' => 'envelope + glass_panels + rad_top/rad_front + max_gpu/max_cooler + form_factor, all from PartDimensions',
            ],
        ];
    }
}