export const categories = [
  { id: "case", label: "Case", file: "case.csv" },
  { id: "cpu", label: "CPU", file: "cpu.csv" },
  { id: "cooler", label: "CPU Cooler", file: "cooler.csv" },
  { id: "motherboard", label: "Motherboard", file: "motherboard.csv" },
  { id: "ram", label: "RAM", file: "ram.csv" },
  { id: "gpu", label: "Graphics Card", file: "gpu.csv" },
  { id: "storage", label: "Storage", file: "storage.csv", multi: true },
  { id: "psu", label: "Power Supply", file: "power-supply.csv" },
  { id: "case-fan", label: "Case Fan", file: "case-fan.csv", multi: true },
  { id: "keyboard", label: "Keyboard", file: "keyboard.csv" },
  { id: "mouse", label: "Mouse", file: "mouse.csv" },
  { id: "monitor", label: "Monitor", file: "monitor.csv", multi: true },
  { id: "speakers", label: "Speakers", file: "speakers.csv" },
  { id: "webcam", label: "Webcam", file: "webcam.csv" },
  { id: "wireless-network-card", label: "Wireless Network Card", file: "wireless-network-card.csv" },
  { id: "headphones", label: "Headphones", file: "headphones.csv" },
  { id: "sound-card", label: "Sound Card", file: "sound-card.csv" },
  { id: "wired-network-card", label: "Wired Network Card", file: "wired-network-card.csv" },
  { id: "thermal-paste", label: "Thermal Paste", file: "thermal-paste.csv" },
  { id: "fan-controller", label: "Fan Controller", file: "fan-controller.csv" },
  { id: "external-hard-drive", label: "External Hard Drive", file: "external-hard-drive.csv" },
  { id: "optical-drive", label: "Optical Drive", file: "optical-drive.csv" },
  { id: "ups", label: "UPS", file: "ups.csv" },
  { id: "streaming", label: "Streaming Equipment", file: "Streaming.csv" },
  { id: "game-controllers", label: "Game Controllers", file: "game-controllers.csv" },
  { id: "flight-simulation", label: "Flight Simulation", file: "flight-simulation.csv" },
  { id: "racing-simulation", label: "Racing Simulation", file: "racing-simulation.csv" },
  { id: "cables-and-accessories", label: "Cables & Accessories", file: "cables-and-accessories.csv" },
];
